### PR TITLE
Add support for variable digits.

### PR DESCRIPTION
**Pull request by fryiee**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Does this need to be GUI? Seems a little weird. Also there is no lang file if it were to be GUI.

**Comment by RyanThompson** [comment]
Comes off as a techy / API config only in which case just add the default value to the $config array in the field type for reference and leave your config get in the schema

**Comment by fryiee** [comment]
I'm not sure I follow - are you saying remove it from config.php, leave it in the schema and then I can still just add it to the config when creating the field migration?

**Comment by RyanThompson** [comment]
Correct

**Pull request merged**
